rust_binary(
    name = "ipsw",
    srcs = [
        "main.rs",
    ],
    deps = [
        "//theos/lib/vfdecrypt:vfdecrypt",
        "//theos/lib/ipsw-downloader:ipsw-downloader",
        "third-party//rust:derive_more",
        "third-party//rust:rootcause",
        "third-party//rust:hex",
        "third-party//rust:plist",
        "third-party//rust:reqwest",
        "third-party//rust:tokio",
        "third-party//rust:indicatif",
        "third-party//rust:clap",
        "third-party//rust:rustls",
        "third-party//by-name/bo/boringssl:bssl-rustls-adapters",
        "third-party//by-name/bo/boringssl:bssl-crypto",
    ],
    visibility = ["PUBLIC"],
)
