load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")

toolchain_alias(
    name = "cxx",
    actual = "toolchains//cxx:cxx",
)

toolchain_alias(
    name = "rust",
    actual = "toolchains//rust:rust",
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)
