load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

common_rustc_flags = [
    # Always abort on panic; do this in tests, too
    '-Cpanic=abort',
    '-Zpanic_abort_tests',

    # don't use the parallel frontend; buck2 isn't jobserver aware, and so
    # this can lead to N processes using N threads a piece, oversubscribing
    # the CPU <https://github.com/facebook/buck2/issues/653>
    '-Zthreads=1',

    # codegen-units=1 improves overall size and performance of generated code
    '-Ccodegen-units=1',

    # always produce stack frames for perf analysis
    '-Cforce-frame-pointers=yes',

    # we need this for tokio-console and other things
    '--cfg=tokio_unstable',
]

rustc_target_triple = select({
    'prelude//os:none': select({
        'prelude//cpu:arm64': 'aarch64-unknown-none',
        'DEFAULT': None,
    }),
    'DEFAULT': None,
})

rustc_flags = select({
    'mode//:build-mode[debug]': common_rustc_flags + [
        '-Cdebuginfo=line-tables-only',
        '-Coverflow-checks=true',
    ],
    'mode//:build-mode[release]': common_rustc_flags + [
        '-Cdebuginfo=line-tables-only',
        '-Cdebug-assertions=false',
        '-Coverflow-checks=false',
    ] + select({
        'prelude//os:none': [ '-Copt-level=z' ],
        'DEFAULT': [ '-Copt-level=3' ],
    }),
})

system_rust_toolchain(
    name = 'rust',
    default_edition = '2024',
    rustc_target_triple = rustc_target_triple,
    rustc_flags = rustc_flags,
)